language: android
android:
  components:
    - tools                 # add this line if you want to use the lates build tools
    - build-tools-23.0.3    # add this line if you want to use the lates build tools
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - android-sdk-license-5be876d5

jdk:
  - oraclejdk8

notifications:
  email: false
